### ISSUE TITLE
App crashes on ShineButton click, NoClassDefFoundError

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [ChadCSong/ShineButton#26]
```
 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/animation/Animator$AnimatorListener$$CC;
                                                       at com.sackcentury.shinebuttonlib.ShineView$3.onAnimationStart(Unknown Source:0)
                                                       at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:990)
                                                       at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1239)
                                                       at android.animation.ValueAnimator.start(ValueAnimator.java:1041)
                                                       at android.animation.ValueAnimator.start(ValueAnimator.java:1065)
                                                       at com.sackcentury.shinebuttonlib.ShineAnimator.startAnim(ShineAnimator.java:38)
                                                       at com.sackcentury.shinebuttonlib.ShineView.showAnimation(ShineView.java:201)
                                                       at com.sackcentury.shinebuttonlib.ShineView.onDraw(ShineView.java:232)
                                                       at android.view.View.draw(View.java:18731)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:17681)
                                                       at android.view.View.draw(View.java:18459)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4184)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3970)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:17672)
                                                       at android.view.View.draw(View.java:18459)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4184)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3970)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:17672)
                                                       at android.view.View.draw(View.java:18459)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4184)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3970)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:17672)
                                                       at android.view.View.draw(View.java:18459)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4184)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3970)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:17672)
                                                       at android.view.View.draw(View.java:18459)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:4184)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3970)
                                                       at android.view.View.draw(View.java:18734)
                                                       at com.android.internal.policy.DecorView.draw(DecorView.java:763)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:17681)
                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:636)
                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:642)
                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:750)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2975)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2789)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2356)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1385)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6729)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:886)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:698)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:633)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
                                                       at android.os.Handler.handleCallback(Handler.java:769)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6535)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at ```
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.animation.Animator$AnimatorListener$$CC" on path: DexPathList[[zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/base.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_dependencies_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_0_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_1_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_2_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_3_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_4_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_5_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_6_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_7_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_8_apk.apk", zip file "/data/app/...-YaVovrqzuZuLptV57qTLUQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app...-YaVovrqzuZuLptV57qTLUQ==/lib/x86, /system/lib, /system/vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       	... 51 more
```
This crash happens with all the latest updates, i. e. Android Studio 3.0 Canary 4, Java 8, Android O etc. 
It might be due to Java 8 because it is the only thing I haven't tested, but can you please tell me how to fix this bug / fix it?
Great library btw.

**Comment by ChadCSong** [comment]
Quite amazing problem, I will test soon.

**Comment by zhuyingtao** [comment]
@creativecreatorormaybenot how did you solve it? I have a same exception
